# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170307_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='coup_de_coeur',
            field=models.IntegerField(choices=[(0, 'Not favorite'), (1, 'Good'), (2, 'Very good'), (3, 'Best of')], default=0),
        ),
    ]
