# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_recipe_coup_de_coeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='coup_de_coeur',
            field=models.IntegerField(choices=[(0, 'Not favorite'), (1, 'Très bon'), (2, 'Super bon !'), (3, 'Une tuerie !')], default=0),
        ),
    ]
