# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171014_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='trash',
            field=models.BooleanField(default=False, verbose_name='trash'),
        ),
    ]
